### ISSUE TITLE
Add a unit to the "Duration" col

### ISSUE THREAD

**Issue by Bukama** [sormuras/bach#117]
The `Duration" col of the output prints the duration of the build. But there's no unit printed so you don't know if the number shows you ms, s or lightyears.

Mentioned by `TheMrMilchman" in the stream of @nicolaiparlog

**Comment by sormuras** [comment]
_Lightyears a measure of time or space? Spacetime!_

Here's the line:
https://github.com/sormuras/bach/blob/d0597a00182c1a8937da46cd35ab0a767828937c/src/de.sormuras.bach/main/java/de/sormuras/bach/task/SummaryTask.java#L26

Where's the PR? 😉

**Comment by sormuras** [comment]
Done via #118 and friends
