### ISSUE TITLE
Notes from FOSDEM 2020

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#119]
- Replace `synchronized {}` with utilities from https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/package-summary.html
- Enforce Java version in project model -- bail out early if requirement is not met.
- When (re-)implementing MRJAR support, consider to mimic the target layout for the source layout: `src/MODULE/main/java/7[8|9|...N]/<types>` instead of `.../java-7/<types>`.
- Flatten `Call` - `Plan` interface hierachy into a single `static final class`/`record` one?

**Comment by sormuras** [comment]
@forax -- something like this?

```java
record Task(Runnable action, List<Task> subtasks) {}
```

instead of resorting to interfaces and two implementations? Like:


```java
interface Task { Runnable action(); }
interface Tasks extends Task { List<Task> subtasks(); }
record SingleTask implements Task (Runnable action) {}
record MultiTask implements Tasks (Runnable action, List<Task> subtasks) {}
```

**Comment by forax** [comment]
Yes !
You don't need subtypes to implement recursive types !

**Comment by sormuras** [comment]
Understood.
