### ISSUE TITLE
Silent download possible?

### ISSUE THREAD

**Issue by karussell** [sormuras/bach#13]
Thanks for your nice tool! Currently trying it out a bit.

It looks although curl should download silently it stills logs heavily:

```
Saving to: ‘jdk-10_linux-x64_bin.tar.gz’
     0K .......... .......... .......... .......... ..........  0% 46.1M 7s
    50K .......... .......... .......... .......... ..........  0% 33.9M 9s
   100K .......... .......... .......... .......... ..........  0% 37.6M 9s
   150K .......... .......... .......... .......... ..........  0%  109M 7s
```

**Comment by sormuras** [comment]
I'm in the middle of rewriting the script - I'll add a silent and already added a verbose mode switch.

**Comment by karussell** [comment]
Oh, nice. Thanks for this and the fast response :)

**Comment by karussell** [comment]
BTW: is there a possibility to use a proper cacert file for openJDK10? Currently this is not really useable for many purposes that request https stuff, see this: https://travis-ci.org/graphhopper/graphhopper/jobs/363503464 where it produces: 

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by sormuras** [comment]
On Debian/Ubuntu (includes Travis CI) try the '-C' option. It'll copy and use the system's default certificates.

**Comment by karussell** [comment]
Cool, works - really nice!

**Comment by karussell** [comment]
This is strange, here you can see there is lots of lines printed: https://travis-ci.org/graphhopper/graphhopper/jobs/363503464#L514

**Comment by sormuras** [comment]
`"group": "edge",` is a potential diff that matters. Comparing:

- bach https://travis-ci.org/sormuras/bach/jobs/363351264/config
- graphhopper https://travis-ci.org/graphhopper/graphhopper/jobs/363517010/config

**Comment by karussell** [comment]
Oh, interesting. But changing this:

https://travis-ci.org/graphhopper/graphhopper/jobs/363567827/config

does not fix it:

https://travis-ci.org/graphhopper/graphhopper/jobs/363567827#L513
