### ISSUE TITLE
Precompile module descriptors

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#149]
Precompile `module-info.java` files to replace regex-based parsing.

**Comment by sormuras** [comment]
See the static `read` methods provided by [`ModuleDescriptor`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/module/ModuleDescriptor.html) that read binary forms.

**Comment by Michael1993** [comment]
I've fiddled with this a bit, but it's not as straightforward as I thought. I've tried compiling just the `module-info.java` files with [jscc](https://github.com/verhas/jscc), but the compiler throws an error if the required/exported packages are not present? :sob:

Any pointers on how to proceed?

**Comment by sormuras** [comment]
- Provide the entire module-source-path so that `javac` sees all packages and other local modules.
- Don't use `--module` option -- pass all `module-info.java` as single arguments.
- Read the generated `module-info.class` files via `ModuleDescriptor.read(...)`.

That's my plan.

**Comment by sormuras** [comment]
This seems to be able to cast the desired magic.

```java
  private Map<String, ModuleDescriptor> computeDescriptors() {
    var classes = directory.resolve(".bach/workspace/.lookup");
    var runner = new ToolRunner(ModuleFinder.ofSystem());
    var paths = new ArrayList<Path>();
    for (var glob : moduleSourcePaths) {
      Paths.find(directory, glob + "/module-info.java", paths::add);
      runner.run(
          Command.builder("javac")
              .with("--module-source-path", glob)
              .with("-implicit:none")
              .with("-d", classes)
              .withEach(paths)
              .build());
    }
    // ModuleFinder.of(classes) --> does not work as packages and friends are missing
    paths.clear();
    var map = new TreeMap<String, ModuleDescriptor>();
    Paths.find(classes, "**/module-info.class", paths::add);
    for (var file : paths) try {
      var descriptor = ModuleDescriptor.read(ByteBuffer.wrap(Files.readAllBytes(file)));
      map.put(descriptor.name(), descriptor);
    } catch (Exception exception) {
      throw new RuntimeException(exception);
    }
    return Map.copyOf(map);
  }
```

**Comment by sormuras** [comment]
Does not work - as soon as external dependences are in play, `javac` bails out:

```
    test.modules\test\java\module-info.java:3: error: module not found: org.junit.jupiter
      requires org.junit.jupiter;
                        ^
    test.base\test\java\module-info.java:2: error: module not found: org.junit.jupiter
      requires org.junit.jupiter;
                        ^
```

Regex's are my best friends and are here to stay.
