### ISSUE TITLE
Classes from deleted source files are not deleted

### ISSUE THREAD

**Issue by jbee** [sormuras/bach#158]
This is based on my observations. 

I made some changes to the main space code. When running tests on console the test run failed due to compile errors in test classes. This only occurs locally due to existing outdated class files that aren't used.

Is there a _clean_ operation one can use?

Shouldn't the javac recognise the changes and recompile the classes? Something seems off.

**Comment by sormuras** [comment]
`javac` only checks the `.java`-`.class` direction for outdated source files. This seems to be code ...

https://github.com/openjdk/jdk/blob/76baa501faa11c934f7ee8e463e13d098ef90518/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Arguments.java#L426-L435

... handling the `--module` option.

>   `--module <module>(,<module>)*, -m <module>(,<module>)*`
>        Compile only the specified module(s), check timestamps

If I understand the logic correctly, a `.class`-`.java` file check is required the prune orphaned class files.

Possible solutions:
- Always clean the classes (`-d`) directory before calling `javac`
- After each `javac` call with the `--module` option used, loop over all `.class` files to find orphaned classes. Perhaps the optional [`SourceFile` Attribute](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.10) may help here.

**Comment by sormuras** [comment]
See also http://mail.openjdk.java.net/pipermail/jigsaw-dev/2020-July/014545.html

**Comment by jbee** [comment]
I doubt javac will clean files any time soon so we should start to think how bach can detect and address the issue

**Comment by sormuras** [comment]
Sure. Stale classes, especially in main code space, are no good.

What about these new [`Flag`](https://github.com/sormuras/bach/blob/master/src/de.sormuras.bach/main/java/de/sormuras/bach/Flag.java)s?

```java
DELETE_COMPILED_CLASSES_[NEVER, ALWAYS, STALE]
```

- `NEVER` is the current behaviour -- `javac` is in control
- `ALWAYS` is the "green fields" approach by-passing all "caching" provided by `javac`
- `STALE` try to detect and delete stale classes -- as first approach, all compiled classes are deleted when a single stale class is detected

**Comment by sormuras** [comment]
I decided to provide a programmatic approach.

```java
    Bach.of(project)
        .build(
            bach -> {
              bach.deleteClassesDirectories();
              bach.executeDefaultBuildActions();
            });
```
