### ISSUE TITLE
Integrate unix4j library

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#18]
Or at least provide an example how to use https://github.com/tools4j/unix4j

**Comment by jbduncan** [comment]
@sormuras I'd be very interested to understand why you want to integrate Bach with unix4j and in what way they'd be integrated together. Would you mind going into more detail about this? :)

**Comment by sormuras** [comment]
`Bach` sports some very basic file system utility helpers in `Bach.Util` that `java.nio.files.Files` does lack ... but sometimes you need to prepare your workspace before a build or do some aftermath as last step of the build. That's when you resort to OS-specific commands. Or you use a platform-agnostic library as `unix4j`.

**Comment by jbduncan** [comment]
@sormuras Thank you very much for the clarification!

I admit that I don't fully understand yet how shell/command-line scripts or "unix4j" would be useful for tasks like preparing a workspace before a build or finalising things towards the end of a build. Could you give a concrete example or two?

**Comment by sormuras** [comment]
Replacing strings in files with "sed", using "find" command instead of `Files.walk` with a predicate...

It's just an option.

**Comment by jbduncan** [comment]
Cool, I understand fully now, thanks! :)

**Comment by sormuras** [comment]
An option that was never ever really needed (by me) - using classes and tools built into Java 11 are sufficient.
