### ISSUE TITLE
Allow separate Java release version for test space

### ISSUE THREAD

**Issue by jbee** [sormuras/bach#190]
After thinking about it I think it is valid to want to use another java version in test space than the one in main space.

For example I would want to set main space to 8 and test space to 16. As bach requires 16 anyhow to build the project it only makes sense that running tests would also require 16. Given that, why now allow use of 16 in the code of the test space itself?

This for example would have an effect on the generated IDEA files so that IDEA is in on it letting you use the configures java version in test space.

**Comment by sormuras** [comment]
Currently, no explicit `--release RELEASE` is passed to the `javac` call used in test space. Therefore, the current JDK determines the Java SE release version of the test space.

#### JDK 16

- main:  `16 .. 7` (7 is deprecated)
- test: `16`

#### JDK 17

- main:  `17 .. 8` (7 was removed)
- test: `17`

#### JDK N

- main:  `N .. n`
- test: `N`

**Comment by jbee** [comment]
Then the only thing left is to consider this accordingly when generating the IDEA files ;)

**Comment by sormuras** [comment]
I agree. That'll be addressed in #70.
