### ISSUE TITLE
Fix module source path computation

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#197]
> For one module it worked, but as soon as I specify two, `javac` starts to complain.

_Originally posted by @Thihup in https://github.com/sormuras/bach/issues/196#issuecomment-767277320_

Wrong: `--module-source-path foo=foo/src/main/java:bar=bar/api/src/main/java`

Correct: `--module-source-path foo=foo/src/main/java --module-source-path bar=bar/api/src/main/java`

Solution: generate a dedicated `--module-source-path` pair for each module.

**Comment by sormuras** [comment]
Fixed via https://github.com/sormuras/bach/commit/50947ec2e98318a867d665fdbb3fddcaf8c040c9

@Thihup - can you please give Bach 16-ea+50947ec a try? It should update itself by calling `jshell https://github.com/sormuras/bach/raw/releases/16/build` as described in #196

**Comment by Thihup** [comment]
Sure, with this patch it worked just fine. Thanks!
