### ISSUE TITLE
Feature: add tweaks to specific modules

### ISSUE THREAD

**Issue by Thihup** [sormuras/bach#198]
For instance, using the `jar --main-class`.

Something like:
```java
tweaks = {
   @Tweak(tool = "jar", with = {"--main-class", "com.foo.bar.Main"}, modules = {"com.foo.bar"}},
   @Tweak(tool = "jar", with = {"--main-class", "com.foo.baz.Main"}, modules = {"com.foo.baz"}},
}
```

**Comment by sormuras** [comment]
An interesting idea. The suggested `modules` field would work like a filter, with an empty array as the default, meaning "tweak all tool calls".

Although I consider Bach 16 feature-freezed, I might add this tiny tweak tweak. 😉

**Comment by sormuras** [comment]
Erm. Was about implement this feature and found:

https://github.com/sormuras/bach/blob/releases/16/com.github.sormuras.bach/main/java/com/github/sormuras/bach/Builder.java#L281

Can you please try:

```java
tweaks = {
   @Tweak(tool = "jar(com.foo.bar)", with = {"--main-class", "com.foo.bar.Main"}},
   @Tweak(tool = "jar(com.foo.baz)", with = {"--main-class", "com.foo.baz.Main"}},
}
```

Same goes for `junit(MODULE)` tweaks.

**Comment by Thihup** [comment]
Well, that worked 😄 
Thanks!
