### ISSUE TITLE
Display download statistics

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#232]
Like total downloads: `https://img.shields.io/github/downloads/sormuras/bach/total`

![GitHub all releases](https://img.shields.io/github/downloads/sormuras/bach/total)

More? https://shields.io/category/downloads

**Comment by onemanagency** [comment]
![GitHub all releases](https://img.shields.io/github/downloads/sormuras/bach/total)
![GitHub all releases](https://img.shields.io/github/downloads/sormuras/bach/17-ea-4/total)
