### ISSUE TITLE
JDK 16 removed by Github Actions

### ISSUE THREAD

**Issue by Tigermouthbear** [sormuras/bach#246]
### Issue Description
Earlier today Github Actions removed the JDK 16 urls from install-jdk.properties, therefore jdk 16 can no longer be used.

### Commit causing issue
5b057a2

**Comment by sormuras** [comment]
Thanks for raising this issue. Should be fixed by https://github.com/sormuras/bach/commit/37724d96311671114f054c52be5728952519de0f and be updated automatically soon.
