### ISSUE TITLE
Fix url in install-jdk.sh

### ISSUE THREAD

**Issue by Qendolin** [sormuras/bach#249]
The script still references the master branch and should point to release11 instead.
https://github.com/sormuras/bach/blob/f44c2b1e8607281a5e10b639b3d8c90a7e9faa12/install-jdk.sh#L198

**Comment by sormuras** [comment]
Thanks for reporting this "copy and paste" @Qendolin

Updated the URL as one of the last changes made to the script. See #248 for details.
