### ISSUE TITLE
All JDK installs are broken in travis

### ISSUE THREAD

**Issue by benwaffle** [sormuras/bach#250]
Hey @sormuras , as you know, travis-ci's JDK installer depends on this repo. I believe they are running the install-jdk.sh script without https://github.com/sormuras/bach/commit/d9aa8c6f2a4241d8121baefe186515fd3fbd6108. Because they are using the wrong file path, it seems that all JDK installations across Travis CI have broken. They are [extremely slow](https://travis-ci.community/t/update-install-jdk-sh-with-the-new-revision/12761) to fix their script.

Would you be open to creating a `master` branch with only the `install-jdk.properties` file included as a temporary solution until Travis can fix it on their end?

**Comment by benwaffle** [comment]
> So, how do we get to know when they fixed their JDK installation management?
> As soon as when I delete master branch next time ... I guess.

yeah, either that, or we can probably spin up a travis build that checks their provided install-jdk.sh

**Comment by benwaffle** [comment]
@sormuras So, do you need any more convincing or discussion? Only you have the ability to create the new branch.

**Comment by sormuras** [comment]
Created https://github.com/sormuras/bach/tree/master on current https://github.com/sormuras/bach/tree/releases/11 and intend to delete it by the end of this month.

**Comment by benwaffle** [comment]
Thank you, much appreciated! I will ping travis-ci's support to try to get this fixed on their end.

**Comment by benwaffle** [comment]
For transparency, this is what support responded:

> Thank you for your reply and apologies for latency in response.
> 
> The repository responsible for setting up the JDK version on our side is https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_install_jdk.bash. I have opened a PR for the URL fix here https://github.com/travis-ci/travis-build/pull/2014 but we are discussing this matter internally and hopefully, we will have a fix on the issue in the time-frame provided by the maintainer.
> 
> Please accept my apologies for the inconvenience this has caused.
>

**Comment by leevida** [comment]
FYI, there's also a discussion on Travis CI forums about this issue: https://travis-ci.community/t/update-install-jdk-sh-with-the-new-revision/12761

**Comment by sormuras** [comment]
Something is brewing, I guess.

![image](https://user-images.githubusercontent.com/2319838/159911462-914b4985-6813-4d18-9314-1156e6dadf18.png)

**Comment by sormuras** [comment]
> So, how do we get to know when they fixed their JDK installation management?
> As soon as when I delete master branch next time ... I guess.

Next week, we'll find out.

**Comment by benwaffle** [comment]
https://github.com/travis-ci/travis-build/commit/866098fa046662b1b4d4e82095f30e0f8d515513 - They've switched from `master` to `releases/11` for the installation. I still opened https://github.com/travis-ci/travis-build/pull/2016 and https://github.com/travis-ci/bach/pull/1 to point their scripts to their own fork.

**Comment by sormuras** [comment]
Now, they need to update `install-jdk.properties` when needed...

Or switch to an external and managed tool, like SDKMAN! or jabber or ...

**Comment by sormuras** [comment]
Heads up: deleted `master` branch moments ago.
