### ISSUE TITLE
JDK 10 download URL failes to connect to jdk.java.net port 80: Connection timed out

### ISSUE THREAD

**Issue by mmoayyed** [sormuras/bach#26]
```bash
0.01s$ unset -v _JAVA_OPTIONS
before_script.2
0.20s$ wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
--2018-08-10 20:17:03--  https://github.com/sormuras/bach/raw/master/install-jdk.sh
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh [following]
--2018-08-10 20:17:03--  https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9544 (9.3K) [text/plain]
Saving to: ‘install-jdk.sh’
     0K .........                                             100%  108M=0s
2018-08-10 20:17:03 (108 MB/s) - ‘install-jdk.sh’ saved [9544/9544]
$ source install-jdk.sh -F 10 -L BCL
install-jdk.sh 2018-07-17
curl: (7) Failed to connect to jdk.java.net port 80: Connection timed out
```

Build failure on travis:
https://travis-ci.org/apereo/cas/jobs/414672861

Has the URL changed?

**Comment by mmoayyed** [comment]
It continues to fail. Another restart attempt: https://travis-ci.org/apereo/cas/jobs/414906374

**Comment by sormuras** [comment]
Prior to the `curl` timeout there's already another one: https://travis-ci.org/apereo/cas/jobs/414906374#L521

```
...
Downloading https://services.gradle.org/distributions/gradle-4.9-bin.zip
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
...
```

**Comment by sormuras** [comment]
Perhaps same underlying reason as in #27 -- http://jdk.java.net/ has some serious troubles.

**Comment by mmoayyed** [comment]
I believe we are back in business: https://travis-ci.org/apereo/cas/jobs/415041864 Thanks for the follow-up.

**Comment by mmoayyed** [comment]
Also for anyone else, this may also be related: https://www.traviscistatus.com/incidents/hgmftqkw1sdl

**Comment by mmoayyed** [comment]
This seems to be very much a hit and miss type of this; here is another failing build restarted around 30 mins ago:
https://travis-ci.org/apereo/cas/jobs/415326566

**Comment by sormuras** [comment]
Non-`sudo`, i.e. Docker-based, builds are running fine.

Seems like the **"Builds with `sudo: required` intermittently failing on travis-ci.com and travis-ci.org"** is the cause for this issue.

_We have taken measures to mitigate the slowness in build processing and start times and are continuing to investigate the networking errors._

**Comment by mmoayyed** [comment]
This continues to manifest, even after Travis CI fixes:
https://travis-ci.org/apereo/cas/jobs/415326421

Do we need to switch back to Travis CI's way of downloading JDK 10, 11, etc? 

Strangely enough, this only happens for certain builds. This job for instance, part of the same build ran through just fine:
https://travis-ci.org/apereo/cas/jobs/415326419

Sort of an indicator that the JDK download site is still somewhat wonky?
