### ISSUE TITLE
No longer fetches JDK11

### ISSUE THREAD

**Issue by Pr0methean** [sormuras/bach#27]
This no longer works for downloading early-access builds of OpenJDK 11. It gives:
```
install-jdk.sh 2018-07-17
Expected feature release number in range of 9 to 10, but got: 11
```
This may have been caused by a change to Oracle's site.

**Comment by joel-costigliola** [comment]
This broke assertj build too https://travis-ci.org/joel-costigliola/assertj-core/jobs/415015933#L409

**Comment by sormuras** [comment]
http://jdk.java.net/ seems to have problems:

![image](https://user-images.githubusercontent.com/2319838/43998631-567ebbce-9dfa-11e8-9af2-b2161c38cc90.png)

http://jdk.java.net/10 yields a `403 Forbidden`
http://jdk.java.net/11 even a `404 Not Found`

**Comment by Pr0methean** [comment]
Will do, but I'd also suggest adding a mirror site for the script to use as a backup, assuming such a mirror can be found. (web.archive.org may work, but it doesn't automatically archive the files.)

**Comment by sormuras** [comment]
Builds are passing.

**Comment by sormuras** [comment]
And again...

...reopening the issue until it works again.

**Comment by karussell** [comment]
A more stable website could be this one ;) https://twitter.com/shipilev/status/1030016721560788994

**Comment by sormuras** [comment]
Sure.

Btw. you may always resort to using the `url` option with `install-jdk.sh`:

`source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu10.3+5-jdk10.0.2-linux_x64.tar.gz`
or
`source install-jdk.sh --url https://download.java.net/java/.../...-linux_x64.tar.gz`
or
...

**Comment by sormuras** [comment]
Builds are passing and according to Mark: _**"Root cause identified and fixed."**_

https://twitter.com/mreinhold/status/1030100677031161856

**Comment by rhanton** [comment]
Maybe should reopen - this no longer works on jdk.java.net for anything below 18. Damn Oracle.
