### ISSUE TITLE
Support for decompressing jdk.tar.xz

### ISSUE THREAD

**Issue by karussell** [sormuras/bach#29]
If you specify this as URL: https://builds.shipilev.net/openjdk-shenandoah-jdk8/openjdk-shenandoah-jdk8-latest-x86_64-release.tar.xz it fails via

> gzip: stdin: not in gzip format

But when using tar ala:

`tar -xf file.tar.xz`

it works, as recent versions auto detect the compression. Or one can use the explicit flag `-J` and auto detect the ending in the script.

**Comment by sormuras** [comment]
Care to create a PR?

**Comment by karussell** [comment]
Yes, did. But it is the lazy version where I just removed `-z`. Not sure how portable this is.

**Comment by sormuras** [comment]
Great. Let's see how it works out on Travis CI...
