### ISSUE TITLE
GraalVM support? 

### ISSUE THREAD

**Issue by sureshg** [sormuras/bach#31]
GraalVM has a different release schedule/versioning than OpenJDK. The work is still being done for JDK 11 support. Does it make sense to adds support [GraalVM oss binaries](https://github.com/oracle/graal/releases) in `install-jdk.sh`? Graal is super interesting because of it's `native-image` (java AOT) generation feature.

**Comment by sormuras** [comment]
Graal, Zulu, ... are already installable via the `--url` option.

https://github.com/sormuras/sormuras.github.io/blob/5fe022a9d7616dbcf2c33884f23d6f3505aa48bc/.travis.yml#L39-L47

I want to keep the focus on OpenJDK for now. May be an option like: "--vendor" would make sense, soon.

**Comment by sormuras** [comment]
`install-jdk.sh` only support OpenJDK distros natively.

The `--url` option is the way to go for GraalVM and other distros.
https://travis-ci.org/sormuras/sormuras.github.io/jobs/541421831#L457
