### ISSUE TITLE
If -c is specified it should check if cacerts file exists before a soft link

### ISSUE THREAD

**Issue by karussell** [sormuras/bach#34]
And if it does not exist it should fail loud and maybe not adding the java to the PATH etc

https://github.com/sormuras/bach/blob/master/install-jdk.sh#L291

BTW: shouldn't JDK 10 contain all the necessary certificates already? I can see that the mentioned JEP 319 is marked as "Release 10", ah but the mentioned issue JDK-8196141 is marked as 11 ...

**Comment by sormuras** [comment]
Care to create PR?

**Comment by sormuras** [comment]
With OpenJDK 11 containing most/all needed necessary certificates, I'm seeing that `-c` won't be used that often anymore. Do you think it's worth to fix this issue or just close it for good?

**Comment by karussell** [comment]
Yes, I agree :)
