### ISSUE TITLE
Why no more support for JDK 8

### ISSUE THREAD

**Issue by IEnoobong** [sormuras/bach#38]
Using oraclejdk8 fails with 
> Expected feature release number in range of 9 to 12, but got: 8

**Comment by sormuras** [comment]
Where do you get the error message from?
Using _raw_ `install-jdk.sh`?
Within a CI service job, like Travis CI?

**Comment by IEnoobong** [comment]
Yes, within Travis CI, which uses install-jdk.sh

See
>https://travis-ci.org/IEnoobong/send-it-kotlin/builds/465975680

**Comment by sormuras** [comment]
Seems like bug in the new `xenial` dist @travis-ci offers -- JDK 8 should be pre-installed on the image and not be installed on-the-fly via the script. `install-jdk.sh` only supports JDK 9+ and really shines when it comes to `ea` versions of the OpenJDK.

Please open an issue over here: https://travis-ci.community/c/environments/xenial

**Comment by IEnoobong** [comment]
Alright. Will do. Thanks

**Comment by sormuras** [comment]
You're welcome!
