### ISSUE TITLE
Re-introduce lookup of "current" openjdk URL

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#42]
Lookup current URL of a JDK that is in GA state. Like openjdk11 as of now: http://jdk.java.net/11/

Origin: https://travis-ci.community/t/install-of-oraclejdk11-is-failing/1856/12

**Comment by sormuras** [comment]
The `EA or RC build` block below the hard-wired switch could do the job...

https://github.com/sormuras/bach/blob/master/install-jdk.sh#L205-L208

**Comment by lukehutch** [comment]
Why not simulate a clickthrough of the links on java.oracle.com to find what the latest download link is for each major JDK version?

**Comment by sormuras** [comment]
I will drop support for Oracle JDKs soon. See #33 for details.

**Comment by sormuras** [comment]
Lookup of `openjdk11` using the _raw_ install script works as expected: https://travis-ci.org/sormuras/sormuras.github.io/jobs/481499802

**Comment by mojo2012** [comment]
Still fails for me with:
```
$ export JAVA_HOME=~/openjdk11
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts
install-jdk.sh 2019-04-17
Couldn't determine a download url for 11-GPL on linux-x64
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts" failed and exited with 1 during .
```

**Comment by sormuras** [comment]
@mojo2012 Are you on Travis CI?

Seems like you (or Travis CI) still uses `install-jdk.sh` version `2019-04-17` which was superseded by `2019-04-18` yesterday.

**Comment by sormuras** [comment]
Looks like Travis CI updated to `2019-04-18`: https://travis-ci.org/forax/pro/builds/522041100
