### ISSUE TITLE
Relax the regex for GA builds

### ISSUE THREAD

**Issue by strangemonad-faire** [sormuras/bach#45]
Looks like openjdk 12 just changed their download url scheme. I had been running against the release candidate just fine and the GA release today came out at:

```
https://download.java.net/java/GA/jdk12/GPL/openjdk-12_linux-x64_bin.tar.gz.sha256
https://download.java.net/java/GA/jdk12/GPL/openjdk-12_osx-x64_bin.tar.gz
https://download.java.net/java/GA/jdk12/GPL/openjdk-12_osx-x64_bin.tar.gz.sha256
https://download.java.net/java/GA/jdk12/GPL/openjdk-12_windows-x64_bin.zip
https://download.java.net/java/GA/jdk12/GPL/openjdk-12_windows-x64_bin.zip.sha256
```

Notice the difference with the following where they have `.../jdk${feature}/NUMBER/GPL`

```
https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
https://download.java.net/java/early_access/jdk13/12/GPL/openjdk-13-ea+12_linux-x64_bin.tar.gz
```

Not sure if this is a bug on their part or intended

**Comment by karussell** [comment]
Thanks! I was able to fix the same problem using your provided URL:
`... --url "https://download.java.net/java/GA/jdk12/GPL/openjdk-12_linux-x64_bin.tar.gz"`

**Comment by sormuras** [comment]
Will fix it a couple of hours.

**Comment by sormuras** [comment]
@robilad ... "you" really should find and use a stable pattern or an API that allows getting the binary link to JDK archive respectively. ;-)

**Comment by sormuras** [comment]
Applied a quick-fix. Need to investigate a better regex-based solution ... soon.

Anyone keen on providing a PR?

**Comment by karussell** [comment]
Thanks a lot for your time and work @sormuras !

**Comment by sormuras** [comment]
You're welcome!


Peter <notifications@github.com> schrieb am Fr., 22. März 2019, 14:17:
