### ISSUE TITLE
install-jdk.sh 2019-04-18 fails for OpenJDK 11

### ISSUE THREAD

**Issue by DanySK** [sormuras/bach#48]
I am opening a new issue report as the error looks different than the one in #46 and #47.
```
$ sh install-jdk.sh --target test --feature "11" --license "GPL" --cacerts
install-jdk.sh 2019-04-18
Variables:
  feature = 11
  license = GPL
       os = linux-x64
      url = https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
   status = 200
  archive = /home/danysk/openjdk-11.0.2_linux-x64_bin.tar.gz
Downloading JDK from https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz...

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by sormuras** [comment]
Looks like there's problem with https://download.java.net -- did a simple retry work out? According to https://travis-ci.org/sormuras/sormuras.github.io/builds/522042053 all of "integration tests" are green.

**Comment by sormuras** [comment]
Restarted the "integration tests" and the OpenJDK 11 worked out: https://travis-ci.org/sormuras/sormuras.github.io/jobs/522154941

**Comment by sormuras** [comment]
No further error reports regarding OpenJDK 11 popped-up. Feel free to re-open this issue if you disagree.
