### ISSUE TITLE
Cannot download OpenJDK using install-jdk.sh

### ISSUE THREAD

**Issue by kazuki43zoo** [sormuras/bach#51]
It seems that a certificate error occurs and we can not download it using `install-jdk.sh`.

See https://travis-ci.org/mybatis/thymeleaf-scripting/jobs/525200361 .

Probably exit code '51' is SSL connection error of cURL. (https://curl.haxx.se/docs/manpage.html#51)

## Current Status (inserted by @sormuras)
- 2019-04-27 Underlying reason: `NET::ERR_CERT_COMMON_NAME_INVALID` for all `download.java.net` assets
- 2019-04-28 "Delay applying a temporary workaround until ... mid of the coming week."
- 2019-04-29 Oracle/Mark Reinhold is [working on it ...](https://twitter.com/mreinhold/status/1122796286544097280)

**Comment by sormuras** [comment]
Any more details? Your environment, error message, version of `install-jdk.sh` and the JDK you requested, ...

**Comment by kazuki43zoo** [comment]
I try to access using https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_osx-x64_bin.tar.gz, it is certificate error. But https://download.oracle.com/java/GA/jdk12/33/GPL/openjdk-12_osx-x64_bin.tar.gz can download.

* `download.java.net` -> `download.oracle.com`

Probably this problem belong OpenJDK site because this problem occurred via https://jdk.java.net/archive/.

**Comment by sormuras** [comment]
Thanks for reporting this issue which seems to be related to `java.net`.

I wonder why the script doesn't select the _current_ version `12.0.1`, though. `12` is archived.

**Comment by sormuras** [comment]
Note: the `NET::ERR_CERT_COMMON_NAME_INVALID` message also appears for `12.0.1` from https://jdk.java.net/12/ ... I'll ping some folks at Oracle about it.

**Comment by sormuras** [comment]
On browsing https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.tar.gz this message appears:

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: download.oracle.com

Issuer: DigiCert ECC Secure Server CA

Expires on: 20.09.2019

Current date: 27.04.2019

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIFRjCCBMygAwIBAgIQD5sFRjpvQq+VDNJFVYG9SDAKBggqhkjOPQQDAjBMMQsw
CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSYwJAYDVQQDEx1EaWdp
Q2VydCBFQ0MgU2VjdXJlIFNlcnZlciBDQTAeFw0xODEwMDIwMDAwMDBaFw0xOTA5
MjAxMjAwMDBaMIGfMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEX
MBUGA1UEBxMOUmVkd29vZCBTaG9yZXMxGzAZBgNVBAoTEk9yYWNsZSBDb3Jwb3Jh
dGlvbjEnMCUGA1UECxMeQ29udGVudCBNYW5hZ2VtZW50IFNlcnZpY2VzIElUMRww
GgYDVQQDExNkb3dubG9hZC5vcmFjbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAEPxHlLlMNuyOPCTQg4a/oGV+7Ypjw0ldnhKbDE984e+32Ky7jKByefBqn
SnlOnjB76JdCaS4bjOQopUao2cFiKaOCAzowggM2MB8GA1UdIwQYMBaAFKOd5h/5
2jlPwG7okcuVpdox4gqfMB0GA1UdDgQWBBRgy6XmvjJ+j0zK1p8y0/Ml6+c+DzB9
BgNVHREEdjB0ghNkb3dubG9hZC5vcmFjbGUuY29tghZlcGQtYWthbS11cy5vcmFj
bGUuY29tghZlcGQtYWthbS1jYS5vcmFjbGUuY29tghhlcGQtYWthbS1pbnRsLm9y
YWNsZS5jb22CE2FydS1ha2FtLm9yYWNsZS5jb20wDgYDVR0PAQH/BAQDAgeAMB0G
A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBpBgNVHR8EYjBgMC6gLKAqhiho
dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vc3NjYS1lY2MtZzEuY3JsMC6gLKAqhiho
dHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc3NjYS1lY2MtZzEuY3JsMEwGA1UdIARF
MEMwNwYJYIZIAYb9bAEBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2lj
ZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMHsGCCsGAQUFBwEBBG8wbTAkBggrBgEFBQcw
AYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEUGCCsGAQUFBzAChjlodHRwOi8v
Y2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRFQ0NTZWN1cmVTZXJ2ZXJDQS5j
cnQwCQYDVR0TBAIwADCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB1ALvZ37wfinG1
k5Qjl6qSe0c4V5UKq1LoGpCWZDaOHtGFAAABZjZWQs4AAAQDAEYwRAIgeZSC6IQd
3jT30VDfPHVuxD/F/tnDpulZ2ByxWVNCDK4CIBJafDoSDApcct1ClxZmqHge/T+S
B66ovp55hLmal5F8AHYAh3W/51l8+IxDmV+9827/Vo1HVjb/SrVgwbTq/16ggw8A
AAFmNlZDbgAABAMARzBFAiEA4wt+1d0cTlumA+bZ7BsqmuxW3Nw8198Jy8nUWcOp
axUCIFOTzCjES461/O586Lry0T/lXgFoiqkM7A3Cjy8aTkNQMAoGCCqGSM49BAMC
A2gAMGUCMQDvNSzteAq83+iI2rHPs8r/5TAFISjZoQsU3dCXAoQ9WZkFNqHt/yC2
RaXq8+M6gvACMA2BNjQJDKpuuI5ABEdvSxUIVQH0c2Ur0kQXCVxXw/+ILlEgbJaP
8QgJPCYPp2Wkeg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDrDCCApSgAwIBAgIQCssoukZe5TkIdnRw883GEjANBgkqhkiG9w0BAQwFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0xMzAzMDgxMjAwMDBaFw0yMzAzMDgxMjAwMDBaMEwxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJjAkBgNVBAMTHURpZ2lDZXJ0IEVDQyBT
ZWN1cmUgU2VydmVyIENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE4ghC6nfYJN6g
LGSkE85AnCNyqQIKDjc/ITa4jVMU9tWRlUvzlgKNcR7E2Munn17voOZ/WpIRllNv
68DLP679Wz9HJOeaBy6Wvqgvu1cYr3GkvXg6HuhbPGtkESvMNCuMo4IBITCCAR0w
EgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwNAYIKwYBBQUHAQEE
KDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQgYDVR0f
BDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xv
YmFsUm9vdENBLmNybDA9BgNVHSAENjA0MDIGBFUdIAAwKjAoBggrBgEFBQcCARYc
aHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAdBgNVHQ4EFgQUo53mH/naOU/A
buiRy5Wl2jHiCp8wHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDQYJ
KoZIhvcNAQEMBQADggEBAMeKoENL7HTJxavVHzA1Nm6YVntIrAVjrnuaVyRXzG/6
3qttnMe2uuzO58pzZNvfBDcKAEmzP58mrZGMIOgfiA4q+2Y3yDDo0sIkp0VILeoB
UEoxlBPfjV/aKrtJPGHzecicZpIalir0ezZYoyxBEHQa0+1IttK7igZFcTMQMHp6
mCHdJLnsnLWSB62DxsRq+HfmNb4TDydkskO/g+l3VtsIh5RHFPVfKK+jaEyDj2D3
loB5hWp2Jp2VDCADjT7ueihlZGak2YPqmXTNbk19HOuNssWvFhtOyPNV6og4ETQd
Ea8/B6hPatJ0ES8q/HO3X8IVQwVs1n3aAr0im0/T+Xc=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
-----END CERTIFICATE-----
```

Are _download **.java.net**_ and _download **.oracle.com**_ the same host?

**Comment by sormuras** [comment]
fup2 https://mail.openjdk.java.net/pipermail/web-discuss/2019-April/000567.html

**Comment by vroyer** [comment]
I have the same issue with the following error:
curl: (51) SSL: no alternative certificate subject name matches target host name 'download.java.net'
When connecting to download.java.net, certificate CN does not match, and subject Alt Name is download.oracle.com. So please fix the install script with download.oracle.com.
Thanks.

**Comment by kaklakariada** [comment]
I have the same issue with my travis-ci build (https://travis-ci.org/kaklakariada/portmapper/builds/525556095). I use `openjdk11` in [.travis.yml](https://github.com/kaklakariada/portmapper/blob/master/.travis.yml#L4).

Would be possible to download openjdk from https://adoptopenjdk.net/ instead of https://jdk.java.net? AdoptOpenJDK provides OpenJDK builds with LTS and security updates and has an provides an [API](https://api.adoptopenjdk.net/) for getting the latest versions.

**Comment by karussell** [comment]
The following temporary workaround in install-jdk.sh seems to make it:

```
-    local DOWNLOAD='https://download.java.net/java'
+    local DOWNLOAD='https://download.oracle.com/java'
```

**Comment by sormuras** [comment]
Feels like a band-aid, @karussell -- and I guess, Oracle will fix the underlying issue soon. So, I'll delay applying a temporary workaround until ... mid of the coming week.

For now, you may resort to the `--url` option of `install-jdk.sh`. Here you may specify a `.tar.gz` JDK of your choice. See https://github.com/sormuras/sormuras.github.io/blob/master/.travis.yml#L25-L47 for example usages. AdoptOpenJDK and others are supported.

@Travis-CI should really provide (more) "pre-installed" Java version. Like they do with their **XENIAL** distro. `openjdk10` and `openjdk11` don't rely on `install-jdk.sh`: https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support

**Comment by sormuras** [comment]
@kaklakariada In your case, i.e. when only using `openjdk11` at Travis CI, I recommend using `dist: xenial` and **not** specifying a jdk. You'll get `openjdk11` by default. See https://github.com/sormuras/bach/blob/a962824b95231a27c9a11d55ff946038a7490ec7/.travis.yml for an example.

**Comment by tbroyer** [comment]
@sormuras Fwiw, unfortunately that doesn't work with `language: android` on Travis: only precise and trusty can be used then.

**Comment by sormuras** [comment]
Good to know, Thomas.

But still, I consider this an issue of "other parties": Oracle/java.net and Travis CI. And it shows, that moving JUnit 5 CI builds to @microsoft 's Azure Pipelines was a good move. /cc @brunoborges

Perhaps, users of Travis CI should resort to use _raw_ `install-jdk.sh` for now. With that, you're able to select "every" `.tar.gz` JDK distribution out there. Something like the following `.travis.yml` scaffold loading AdoptOpenJDK 12 (hotspot):

```yml
language: java

before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
- java --version
- // invoke your build tool...
```

**Comment by kaklakariada** [comment]
> 
> 
> @kaklakariada In your case, i.e. when only using `openjdk11` at Travis CI, I recommend using `dist: xenial` and **not** specifying a jdk. You'll get `openjdk11` by default. See https://github.com/sormuras/bach/blob/a962824b95231a27c9a11d55ff946038a7490ec7/.travis.yml for an example.

@sormuras I didn't know that. Thank you very much for the hint!

**Comment by sormuras** [comment]
_"Working on it …"_
https://twitter.com/mreinhold/status/1122796286544097280

**Comment by sormuras** [comment]
From https://jdk.java.net/archive/ to https://jdk.java.net/13/ all download links now start with `https://download.oracle.com` -- will update `install-jdk.sh` accordingly.
