### ISSUE TITLE
Testing In The Modular World

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#53]
https://github.com/sormuras/bach/blob/master/src/bach/Bach.java#L399-L401
```java
      java.add("--class-path");
      java.add(bach.download(Property.TOOL_URI_JUNIT));
      java.add("org.junit.platform.console.ConsoleLauncher");
```

Since JUnit 5 ships as explicit Java modules, this "class-path hack" no longer works. Use the module-path, Luke.

**Comment by sormuras** [comment]
```
java.lang.IllegalAccessError:
class org.junit.platform.launcher.core.LauncherFactory (in unnamed module @0x17baae6e)

cannot access class org.junit.platform.commons.util.Preconditions (in module org.junit.platform.commons)

because module org.junit.platform.commons does not export org.junit.platform.commons.util to unnamed module @0x17baae6e

```

**Comment by fallphenix** [comment]
I used :
`--add-exports org.junit.platform.commons/org.junit.platform.commons.util=ALL-UNNAMED
--add-exports org.junit.platform.commons/org.junit.platform.commons.logging=ALL-UNNAMED`

**Comment by sormuras** [comment]
I don't like those band-aid command line options. Iirc, I already implemented a module-path only solution. Need to double-check that, though.

**Comment by sormuras** [comment]
https://github.com/sormuras/bach/blob/8e70c779025354c159b99fe9f67e1d212f3f867e/src/bach/Bach.java#L1308

The new Bach.Tester implementation takes care of setting up the correct module-path
