### ISSUE TITLE
Remove Oracle JDK support

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#56]
Follow-up from #33 and https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892/4?u=sormuras

### Deliverables
- [x] Remove `BCL` from `license` option
- [x] Remove `9-BCL`, `10-BCL`, and `11-BCL` URLs from script
- [x] Forward to OpenJDK variant ?

**Comment by tellison** [comment]
You can obtain your OpenJDK builds (nightlies or releases) via [the AdoptOpenJDK API](https://api.adoptopenjdk.net/).  No login page etc to go through.

If there is anything missing from there drop a note on the #api channel of [AdoptOpenJDK Slack](https://adoptopenjdk.net/slack.html) and the team can discuss options.

**Comment by sormuras** [comment]
Thanks for the heads-up, Tim.

I'm already using and showing examples how `install-jdk.sh` supports AdoptOpenJDK builds via its API here:

https://github.com/sormuras/sormuras.github.io/blob/686e757e20aff3a32f69b324326213cf3b123758/.travis.yml#L28-L33
```
source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
```

_I wished, https://jdk.java.net/ had a similar API (/cc @robilad) or at least a [look-up table](https://mail.openjdk.java.net/pipermail/web-discuss/2018-May/000533.html) -- so I didn't have to parse their HTML document for the download links..._

Having said that, I don't plan to change `install-jdk.sh`'s API to directly support AdoptOpenJDK, yet. But it would be an easy task for @travis-ci (/cc @banzaiman) to update their scripts accordingly, i.e. map user's configuration settings to a command line as shown above.

**Comment by tellison** [comment]
Hi @sormuras, apologies if I am misreading the script, but it looks like the `11-GPL` download is still [referencing the insecure 11.0.2 build](https://github.com/sormuras/bach/blob/master/install-jdk.sh#L204)?

**Comment by sormuras** [comment]
True.

Here's the gist of our chat:

![image](https://user-images.githubusercontent.com/2319838/60429852-41d43180-9bfc-11e9-8004-d109ca03ab4a.png)

**Comment by sormuras** [comment]
- [x] Remove `BCL` from `license` option
- [x] Remove `9-BCL`, `10-BCL`, and `11-BCL` URLs from script

Done via https://github.com/sormuras/bach/commit/6f245b5e59d19462631db63849d986dc5fa32d18

**Comment by sormuras** [comment]
- [x] Forward to OpenJDK variant

Done via https://github.com/sormuras/bach/commit/a7bb40756c891859d962b18ab4c009c1ef272636

**Comment by sormuras** [comment]
Oracle JDKs are no longer "directly" supported.
