### ISSUE TITLE
Option `--cacerts` fails for AdoptOpenJDK 9 and 10

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#60]
Looks like the archive from AdoptOpenJDK doesn’t contain a `lib/security/cacerts` directory by default.

https://travis-ci.community/t/install-jdk-sh-failing-for-openjdk9-and-10

**Comment by lkloon123** [comment]
Hi, thanks for the fix but apparently this is still not working on `install-jdk.sh 2019-07-02-II`

**Comment by sormuras** [comment]
> I’ve restarted https://travis-ci.org/coala/coala-bears/jobs/553187482 right now and the API is 302 but the result is still `ln: failed to create symbolic link ‘/home/travis/openjdk10/lib/security/cacerts’: No such file or directory`
> https://travis-ci.community/t/install-jdk-sh-failing-for-openjdk9-and-10/3998/18

Will move the `ln` call also into the guarded block.

**Comment by sormuras** [comment]
Done via https://github.com/sormuras/bach/commit/c185fb8aa2d406517228341e3d25168decb5b9ab
