### ISSUE TITLE
AdoptOpenJDK 9 on Travis CI using wrong JAVA_HOME

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#61]
https://travis-ci.org/raphw/byte-buddy/jobs/554632294

Reported by @raphw

**Comment by raphw** [comment]
"We cannot execute /home/travis/openjdk9/bin/java"

**Comment by sormuras** [comment]
The path is set by Travis CI and passed to `install-jdk.sh` via its `--target` option. Seems like the tar extraction doesn't use the right relative path for JDK 9 (and 10?).

**Comment by raphw** [comment]
10 works just fine: https://travis-ci.org/raphw/byte-buddy

**Comment by sormuras** [comment]
Good to know. Then, I suspect a change between how JDK 9 and 10 are tarred by AdoptOpenJDK.

**Comment by sormuras** [comment]
9 works in `raw` mode: https://travis-ci.org/sormuras/sormuras.github.io/jobs/554838766

**Comment by sormuras** [comment]
Superseded by #62
