### ISSUE TITLE
Write tests for install-jdk.sh

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#64]
* Extend/improve `install-jdk-tests.sh`
* Fail GitHub [Actions](https://github.com/sormuras/bach/actions) on errors
* Make use of https://shellspec.info or https://github.com/sstephenson/bats

**Comment by jayvdb** [comment]
The most important test is that the installed version is the one which was requested.

A "pass" is useless unless the test is verifying that the desired version was installed.  I believe this should work according to the readme

```
$ JDK=8 install-jdk.sh
install-jdk.sh 2019-03-23
Variables:
  feature = 14
  license = GPL
       os = linux-x64
      url = https://download.java.net/java/early_access/jdk14/8/GPL/openjdk-14-ea+8_linux-x64_bin.tar.gz
   status = 200
  archive = /home/travis/openjdk-14-ea+8_linux-x64_bin.tar.gz
Downloading JDK from https://download.java.net/java/early_access/jdk14/8/GPL/openjdk-14-ea+8_linux-x64_bin.tar.gz...
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+8-255)
OpenJDK 64-Bit Server VM (build 14-ea+8-255, mixed mode, sharing)
```

**Comment by jayvdb** [comment]
Ugh I see `install-jdk.sh --feature 8` fails - at least it isnt successful at installing 14 instead of requested 8.

**Comment by sormuras** [comment]
Done in https://github.com/sormuras/bach/blob/master/.github/workflows/install-jdk-tests.yml

**Comment by jayvdb** [comment]
I've spot checked https://github.com/sormuras/bach/runs/736770142?check_suite_focus=true and it all looks good.

I was hoping the tests would separately confirm that the result was correct, but accept that may be a bit tough to do, and appreciate that running all varieties is a massive step forward.  Much appreciated.

**Comment by sormuras** [comment]
You're welcome.

> [...] confirm that the result was correct [...]

Thought about that too. What about collecting all results from

https://github.com/sormuras/bach/blob/1c08f117a65c10d410175b45e6929091bd9bec0a/.github/workflows/install-jdk-tests.yml#L18

and compare the http status code being below 400?
