### ISSUE TITLE
OpenJDK support for PPC64LE platform

### ISSUE THREAD

**Issue by ghatwala** [sormuras/bach#68]
Hi @sormuras ,

Found this repo mentioned here - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_install_jdk.bash#L14 . 

I have been trying to add support for power (via travis.yml) in few of communities. For eg- check this travis job for my fork - https://travis-ci.org/ghatwala/commons-codec . Here only openjdk8 works smoothly for ppc64le based jobs as that seems available for ppc64le in travis environments. 

However for other openjdk9/10/11/12 - it downloads for eg. for openjdk10/power builds - https://travis-ci.org/ghatwala/commons-codec/jobs/542165976#L153 .  This x86_64 jdk binary wouldn't work on power and found that this repo is being invoked from travisci/build to run this part of script (install-jdk.sh)
```
 ~/bin/install-jdk.sh --target "/home/travis/openjdk10" --workspace "/home/travis/.cache/install-jdk" --feature "10" --license "GPL" --cacerts
```
Now the query which i had is 

- Noted here that - https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms , ppc64le platform is showing supported for openjdk8/9/10/11/12 . I understand the power/travis jobs run on xenial . What would it take to add downloading/installing openjdk9/10/11/12 for travis jobs running on ppc64le ? Any changes required to be done in "install-jdk.sh" ? 

Please let me of suggestions if any to add openjdk9/10/11/12 for travis/power builds or any of my above understanding is incorrect ?.

**Comment by sormuras** [comment]
Hi @ghatwala -- pardon my late reply.

Can you please first try to make use of the "--url" option offered by "install-jdk.sh"?

If that works, it should be easy to extend the script to support that platform transparently.

**Comment by ghatwala** [comment]
hi @sormuras  - thanks for the response !!
So am unable to find the tarball for those openjdk versions ( for ppc64le + xenial ) here - https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms . Any idea where could we find these may be ?

**Comment by sormuras** [comment]
They aren't listed here neither: https://jdk.java.net
Maybe AdoptOpenJDK provides those?

**Comment by ghatwala** [comment]
@sormuras - yup adoptopenjdk works like a charm for ppc64le . Check here - https://travis-ci.org/ghatwala/bach/builds/568770424 - here versions 8,9,10,11,12 works for ppc64le(via adoptopenjdk + passing URL using "--url").

If everything looks good may be will raise PR after some internal process. Lemme know your thoughts ?

**Comment by sormuras** [comment]
Citing myself from #62:
> `install-jdk.sh` will only serve JDK builds available via https://jdk.java.net
>
> Supporting AdoptOpenJDK "natively", i.e. mapping archived and released JDKs to AdoptOpenJDK API for downloading, will cease ... soon. You may still use AdoptOpenJDK builds via the `--url` option.

I always forget the additional _troubles_ I encounter when supporting more than one contributor.

Thus, closing this issue.

**Comment by ghatwala** [comment]
@sormuras - so for example to install openjdk11 ( from adoptopenjdk) for ppc64le in the travis.yml of my repo will need to do below .. Please confirm if below is correct ?

For example for power + openjdk11 download use below
```
  -  # AdoptOpenJDK -- https://adoptopenjdk.net
    env: JDK=adoptopenjdk11
    script: source ./install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=ppc64le&release=latest&heap_size=normal&type=jdk'
```

**Comment by sormuras** [comment]
You'll need a `os: ppc64le` directive or similar, too.

Looks good to me. Give it a shot and you'll see.
