### ISSUE TITLE
Broken --workspace doesn't work anymore

### ISSUE THREAD

**Issue by szpak** [sormuras/bach#72]
`--workspace` doesn't seem to [work anymore](https://travis-ci.org/szpak/gradle-pitest-plugin/jobs/580233179):
```
$ . gradle/install-jdk.sh -W ~/custom-java --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal"
install-jdk.sh 2019-07-17
Variables:
  feature = <overridden by custom url>
       os = <overridden by custom url>
      url = https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal
   status = 302
Downloading JDK from https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal...
tar: /home/travis/custom-java: Cannot open
```
After local testing it seems that `--output-directory` overrides `--directory-prefix` introduced in [July](https://github.com/sormuras/bach/commit/a7bb40756c891859d962b18ab4c009c1ef272636#diff-08dca971d5e4fbd0624e7bf955f5adb1R252). It started to be visible as I use locally copied install-jdk.sh script which I just upgraded to get support for newer Java versions.

**Comment by sormuras** [comment]
Thanks for the report.

Do you have an idea how to quickly fix this as well? My current time is limited, so I won't be able to dig into for about two weeks.

**Comment by szpak** [comment]
Maybe:
> local local="--output-document=${workspace}jdk-${feature}.tar.gz"
+
> local tar_options="--file ${workspace}jdk-${feature}.tar.gz"
with some trailing "/" adding to workspace if not provided

However, it's Bash, nothing is easy (and testable)... Take your time, maybe I will be determined enough to get into it before that ;).
