### ISSUE TITLE
Java 11 Travis build failed

### ISSUE THREAD

**Issue by kumarkrish85** [sormuras/bach#84]
Hi,

I am using this travis.yml to trigger the source code build 

[https://github.com/kumarkrish85/Cognizant-Intelligent-Test-Scripter/blob/master/.travis.yml](url)

In travis , i am getting the below error it's happening from today. Please help me to resolve the issue

> The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"" failed and exited with 56 during .

Thanks,
Krishna

**Comment by sormuras** [comment]
Same for Java 12, 13, 14-ea ... I guess. See #85 for details.

**Comment by sormuras** [comment]
jdk.java.net is back online.

**Comment by kumarkrish85** [comment]
Thanks @sormuras , it worked.
