### ISSUE TITLE
Java 12 Travis build failed

### ISSUE THREAD

**Issue by jaeyeonling** [sormuras/bach#85]
Hi,

I am using this travis.yml to trigger the source code build

https://github.com/jaeyeonling/korean-syllable-tokenizer/blob/master/.travis.yml

In travis, i am getting the below error it's happening from today. Please help me to resolve the issue

> The command "~/bin/install-jdk.sh --target "/home/travis/openjdk12" --workspace "/home/travis/.cache/install-jdk" --feature "12" --license "GPL" --cacerts" failed and exited with 56 during .

Thanks,
Jaeyeonling

**Comment by sormuras** [comment]
Hm, https://jdk.java.net seems down ... it doesn't respond.

**Comment by sormuras** [comment]
> "...failed and exited with 56..."

Never saw this error code before, iirc. Could it be a timeout code?

**Comment by Siedlerchr** [comment]
Seems to be working again:
https://download.java.net/openjdk/jdk12/ri/openjdk-12+32_linux-x64_bin.tar.gz

**Comment by jaeyeonling** [comment]
Resolved rebuild 

Thanks 💯
