### ISSUE TITLE
Colors, Communication, License & Charts

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#91]
## Colors

- Background `0x3C5884` `60 88 132`
- Foreground `0xC3A77B` `195 167 123`

![Bach](https://user-images.githubusercontent.com/2319838/100900786-7ddf8600-34c3-11eb-93d4-f26d3d3f5ece.png)

**Comment by onemanagency** [comment]
Uniques
 zero installation required (besides JDK 11+, using jshell)
 zero configuration required (conventions and information gathered from module-info.java files)
 customize with properties to override auto-configured values (.bach/project.properties)
 b-y-o-b program using plain old Java (src/bach/Build.java)
 3rd-party modules in plain sight (single lib/ directory)
 compilation is compile (javac) and package (jar) as an atomic step
 multi-module compilation in a single pass (--module-source-path, ${PROJECT.NAME}-javadoc.jar)
 multi-release module are supported (java-7, java-8, ..., java-11, ..., java-N)
 automated checks aka testing built-in (test(${MODULE}),junit)
 deployment support (via ${MODULE}-sources.jar and consumer pom.xml per module)
Zero Installation
Enter the base directory of your Java project, open a shell, and execute one of the following commands:

Long: jshell https://raw.githubusercontent.com/sormuras/bach/master/src/bach/Bach.jsh
Shorter: jshell https://github.com/sormuras/bach/raw/master/src/bach/Bach.jsh
Shortened: jshell https://bit.ly/bach-jsh
That's it.

**Comment by sormuras** [comment]
### Numbers

`bit.ly/bach-jsh`: https://app.bitly.com/Bj1hazAHmoK/bitlinks/2Dga03e
`bintray`: https://bintray.com/sormuras/maven/bach#statistics
`maven`: https://search.maven.org/artifact/de.sormuras.bach/de.sormuras.bach

**Comment by sormuras** [comment]
https://blog.jooq.org/2013/10/09/jooq-3-2-offering-commercial-licensing-and-support/
